name: CI

on:
  - push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./React/.nvmrc
          cache-dependency-path: ./React/package-lock.json
          cache: npm

      - name: Install UI dependencies
        working-directory: ./React
        run: npm ci

      - name: Build UI
        working-directory: ./React
        run: npm run build

      # Build
      - name: Build project
        id: build-game
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          allowDirtyBuild: true
          targetPlatform: ${{ inputs.targetPlatform }}
